### ISSUE TITLE
Cannot see control panel and 404 on @taxonomy endpoint

### ISSUE THREAD

**Issue by jimbiscuit** [eea/volto-taxonomy#17]
I have installed "@eeacms/volto-taxonomy" 3.1.0 on my volto project and "collective.taxonomy" 3.0.1 on my plone project. I use volto 16.18 and plone 6.0.2.

I have two bugs : 
- In Volto I cannot see the control panel to setup the taxo, I see it in plone and I can access http://localhost:3000/controlpanel/taxonomies
- But when I access http://localhost:3000/controlpanel/taxonomies, the endpoint @taxonomy return a 404
```
{
  "message": "Resource not found: http://localhost:3000/@taxonomy",
  "type": "NotFound"
}
```

**Comment by avoinea** [comment]
@jimbiscuit Please upgrade to:
* **collective.taxonomy 3.1+**
*  **volto-taxonomy 4.0.0+**
